### ISSUE TITLE
Normalized device coordinates (NDC) and DirectXMath with z range [-1..+1]

### ISSUE THREAD

**Issue by Joffrey** [Microsoft/DirectXMath#45]
For now, I don't see any option available in DirectXMath to switch to using OpenGL/WebGL (Angle) compatible clip space/NDC space.
It could be really useful.

**Comment by walbourn** [comment]
Which functions in particular are you referring to?

Generally speaking, DirectXMath doesn't care about which space you are using. It always uses row-major matrices, but where handedness comes in it offers both versions. There are a few cases in the collision types where this doesn't quite work out, but otherwise it's trying to be agnostic.

**Comment by Joffrey** [comment]
It's something related to projection matrices.
OpenGL’s clip space extends from −1 to 1 in all three axes with the z-axis pointing out of the screen. DirectX’s z-axis points into the screen, and the near plane is mapped to z=0 rather than z=−1.

**Comment by Joffrey** [comment]
GLM provides a way to switch with the GLM_DEPTH_ZERO_TO_ONE macro.
https://github.com/g-truc/glm/blob/master/glm/gtc/matrix_transform.inl

**Comment by Joffrey** [comment]
```C
		XMMATRIX myProjection =
			  XMMatrixOrthographicOffCenterRH(
				0.0f, 400.0f, 0.0f, 400.0f, -20.0f, 20.0f)
			* XMMatrixScaling(1.0f, 1.0f, 2.0f)
			* XMMatrixTranslation(0.0f, 0.0f, -1.0f)
		;
```

This workaround is probably enough to fit with the opengl renderer NDC.

**Thanks to derhass on IRC freenode ##opengl**
