### ISSUE TITLE
Support Clang - Compiler

### ISSUE THREAD

**Issue by LepelTsmok** [Microsoft/DirectXMath#50]
Hello DirectXMath-Team,

I tried to use DirectXMath in a project of mine. Sadly the clang compiler has a different interpretation of the __m128 type. Is there a way, or could you please make a way, that the clang compiler will be happy with DirectXMath? The appearing error is of the following type:

> C:\Program Files (x86)\Windows Kits\8.1\Include\um\DirectXMath.h(355,29): error : overloaded 'operator+' must have at least one parameter of class or enumeration type
1>  XMVECTOR    XM_CALLCONV     operator+ (FXMVECTOR V);

Thank you and kind regards
LepelTsmok

**Comment by walbourn** [comment]
The Windows 8.1 SDK has version 3.06 of the DirectXMath library, so there have been a lot of changes since then. You should consider moving to a newer Windows 10 SDK or putting a new copy of the DirectXMath library in your include path before the Windows SDK you are using.

A few minor fixes were made for non-Microsoft compilers like clang after the last official release, so you can try out [this](https://github.com/Microsoft/DirectXMath/releases/tag/apr2017) preview. Note that DirectXMath requires a few C++11 language features such as  ``=default`` and ``=delete``.

**Comment by walbourn** [comment]
I defintely need to add a control define for removing the XMVECTOR overloads as those are not portable. Clang will also need the following to silence warnings:

    #pragma clang diagnostic push
    #pragma clang diagnostic ignored "-Wunknown-pragmas"
    #pragma clang diagnostic ignored "-Wmissing-braces"
    #pragma clang diagnostic ignored "-Wunused-value"
    #pragma clang diagnostic ignored "-Wextra-qualification"

    #include "DirectXMath.h"
    #include "DirectXCollision.h"
    #include "DirectXColors.h"
    #include "DirectXPackedVector.h"

    #pragma clang diagnostic pop

**Comment by walbourn** [comment]
The ``__m128`` overloads issue is fixed in [this commit](https://github.com/Microsoft/DirectXMath/commit/d973b9a9aad228225b01c210f8d9520747e9d31c).

**Comment by walbourn** [comment]
Cleaned up the warnings I found when using CLang with Microsoft Codegen (``v140_clang_c2``) in [this commit](https://github.com/Microsoft/DirectXMath/commit/58df665c97d357dab5c35f9a6d6e165ea419755a)
