### ISSUE TITLE
XMVectorNegativeMultiplySubtract does not perform negative multiply subtract

### ISSUE THREAD

**Issue by nfrechette** [Microsoft/DirectXMath#78]
It appears that the name of XMVectorNegativeMultiplySubtract is very misleading as the function does not perform what its name states. It would benefit from being renamed to XMVectorMultiplySubtract or XMVectorNegativeMultiplyAdd.

XMVectorMultiplyAdd(a, b, c) does (a*b)+c
XMVectorNegativeMultiplySubtract(a, b, c) currently does -(a*b)+c (effectively mul/sub or negmul/add)

A true negative multiply subtract such as FMA's _mm_fnmsub_ps(..) cannot be mapped without conflicting with the existing name which uses _mm_fnmadd_ps(..): a negative multiply add.

See here: https://github.com/Microsoft/DirectXMath/blob/ffb2edbd1627e9eec75f68b4ff00e0861ad84ebe/Inc/DirectXMathVector.inl#L3079

**Comment by walbourn** [comment]
Most of the function definitions in DirectXMath date back to xboxmath, which was created for Xbox 360 using an Altivec variant known as VMX128. I've in general not made any breaking changes to the API since that time through xnamath and DirectXMath with respect to what a given function is named and the computation it executes.

The original definition of ``XMVectorNegativeMultiplySubtract`` is from that library which as shown on [Microsoft docs](https://docs.microsoft.com/en-us/windows/desktop/api/directxmath/nf-directxmath-xmvectornegativemultiplysubtract) is:

    XMVECTOR result;
    result.x = V3.x - V1.x * V2.x;
    result.y = V3.y - V1.y * V2.y;
    result.z = V3.z - V1.z * V2.z;
    result.w = V3.w - V1.w * V2.w;
    return result;

Which exactly matched the Xbox 360 VMX128 instruction ``__vnmsubfp(V1, V2, V3)``.

This exactly matches the FMA3 instruction ``_mm_fnmadd_ps(V1, V2, V3)`` as you note.

For ARM/ARM65, it's ``vfmsq_f32( V3, V1, V2 )`` (true-fused ARMv8) or ``vmlsq_f32( V3, V1, V2 )``

The choice of name here is a bit arbitrary, but it really can't be changed without breaking client code.
